import { IAd } from '@/types/models';

// Fixed UUIDs — consistent across module evaluations and page navigations
const mockUserId          = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
const mockCategoryProduct = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
const mockCategoryService = 'cccccccc-cccc-cccc-cccc-cccccccccccc';
const mockIndustry        = 'dddddddd-dddd-dddd-dddd-dddddddddddd';

export const MOCK_ADS: Partial<IAd>[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    title: 'Precision Emerald Timepiece',
    description: 'Expertly crafted luxury watch with an emerald green sunburst dial and premium leather strap. A masterpiece of horology for the discerning collector.',
    imageUrl: '/images/watch.png',
    webLink: 'https://yubbox.com',
    ownerName: 'James Wilson',
    location: 'Geneva, Switzerland',
    companyName: 'Wilson & Co. Horology',
    countries: ['CH', 'GB', 'US'],
    categoryId: mockCategoryProduct,
    industryId: mockIndustry,
    userId: mockUserId,
    isActive: true,
    isPaid: true,
    yubboxCount: 124,
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    title: 'Next-Gen Quantum Smartphone',
    description: 'Experience the future with our most powerful smartphone yet. Featuring a 240Hz holographic display and advanced neural processing unit.',
    imageUrl: '/images/phone.png',
    webLink: 'https://yubbox.com',
    ownerName: 'Sarah Chen',
    location: 'Silicon Valley, CA',
    companyName: 'Quantum Tech Labs',
    countries: ['US', 'JP', 'KR'],
    categoryId: mockCategoryProduct,
    industryId: mockIndustry,
    userId: mockUserId,
    isActive: true,
    isPaid: true,
    yubboxCount: 89,
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    title: 'Global Digital Growth Strategy',
    description: 'Scale your business globally with our data-driven digital marketing solutions. Specialized in SEO, PPC, and cross-border e-commerce transformation.',
    imageUrl: '/images/digital.png',
    webLink: 'https://yubbox.com',
    ownerName: 'Robert Vance',
    location: 'London, UK',
    companyName: 'Vance Digital Agency',
    countries: ['GB', 'DE', 'FR', 'AE'],
    categoryId: mockCategoryService,
    industryId: mockIndustry,
    userId: mockUserId,
    isActive: true,
    isPaid: true,
    yubboxCount: 256,
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '44444444-4444-4444-4444-444444444444',
    title: 'Sustainable Smart Home Hub',
    description: 'The central brain for your eco-friendly home. Monitor energy usage, control appliances, and optimize your carbon footprint with AI insights.',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    webLink: 'https://yubbox.com',
    ownerName: 'Elena Rodriguez',
    location: 'Madrid, Spain',
    companyName: 'EcoSmart Solutions',
    countries: ['ES', 'PT', 'FR'],
    categoryId: mockCategoryProduct,
    industryId: mockIndustry,
    userId: mockUserId,
    isActive: true,
    isPaid: true,
    yubboxCount: 45,
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '55555555-5555-5555-5555-555555555555',
    title: 'Artisan Coffee Roasters Collective',
    description: 'Direct trade beans sourced from family-owned farms. Roasted in small batches to preserve unique regional flavor profiles and aromas.',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    webLink: 'https://yubbox.com',
    ownerName: 'Marco Rossi',
    location: 'Florence, Italy',
    companyName: "L'Artigiano Coffee",
    countries: ['IT', 'AT', 'CH'],
    categoryId: mockCategoryProduct,
    industryId: mockIndustry,
    userId: mockUserId,
    isActive: true,
    isPaid: true,
    yubboxCount: 78,
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '66666666-6666-6666-6666-666666666666',
    title: 'CloudScale Infrastructure Management',
    description: 'Enterprise-grade cloud solutions powered by AI. Optimize your server costs, enhance security, and scale your applications globally with 99.99% uptime.',
    imageUrl: '/images/cloud.png',
    webLink: 'https://yubbox.com',
    ownerName: 'David Miller',
    location: 'Austin, TX',
    companyName: 'CloudScale Systems',
    countries: ['US', 'CA', 'GB'],
    categoryId: mockCategoryService,
    industryId: mockIndustry,
    userId: mockUserId,
    isActive: true,
    isPaid: true,
    yubboxCount: 142,
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '77777777-7777-7777-7777-777777777777',
    title: 'Aura Architectural Design Studio',
    description: 'We create living spaces that inspire. Specialized in luxury residential projects and sustainable commercial spaces with a focus on natural light.',
    imageUrl: '/images/architecture.png',
    webLink: 'https://yubbox.com',
    ownerName: 'Sophie Larousse',
    location: 'Paris, France',
    companyName: 'Aura Design',
    countries: ['FR', 'BE', 'LU'],
    categoryId: mockCategoryService,
    industryId: mockIndustry,
    userId: mockUserId,
    isActive: true,
    isPaid: true,
    yubboxCount: 187,
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '88888888-8888-8888-8888-888888888888',
    title: 'Serenity Wellness Coaching',
    description: 'Transform your life with personalized wellness plans. We offer integrated physical health and mental clarity coaching in premium studio environments.',
    imageUrl: '/images/wellness.png',
    webLink: 'https://yubbox.com',
    ownerName: 'Emma Thompson',
    location: 'Vancouver, Canada',
    companyName: 'Serenity Wellness',
    countries: ['CA', 'US', 'AU'],
    categoryId: mockCategoryService,
    industryId: mockIndustry,
    userId: mockUserId,
    isActive: true,
    isPaid: true,
    yubboxCount: 95,
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const MOCK_CATEGORIES = [
  { id: mockCategoryProduct, name: 'Premium Products', slug: 'products', type: 'product' as const },
  { id: mockCategoryService, name: 'Strategic Services', slug: 'services', type: 'service' as const },
];
