import { IAd } from '@/types/models';
import mongoose from 'mongoose';

const mockUserId = new mongoose.Types.ObjectId();
const mockCategoryProduct = new mongoose.Types.ObjectId();
const mockCategoryService = new mongoose.Types.ObjectId();
const mockIndustry = new mongoose.Types.ObjectId();

export const MOCK_ADS: Partial<IAd>[] = [
  {
    _id: new mongoose.Types.ObjectId(),
    title: 'Precision Emerald Timepiece',
    description: 'Expertly crafted luxury watch with an emerald green sunburst dial and premium leather strap. A masterpiece of horology for the discerning collector.',
    imageUrl: '/images/watch.png',
    webLink: 'https://yubbox.com',
    ownerName: 'James Wilson',
    location: 'Geneva, Switzerland',
    companyName: 'Wilson & Co. Horology',
    countries: ['CH', 'GB', 'US'],
    categoryId: mockCategoryProduct as unknown as mongoose.Types.ObjectId,
    industryId: mockIndustry as unknown as mongoose.Types.ObjectId,
    userId: mockUserId as unknown as mongoose.Types.ObjectId,
    isActive: true,
    isPaid: true,
    yubboxCount: 124,
    expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: 'Next-Gen Quantum Smartphone',
    description: 'Experience the future with our most powerful smartphone yet. Featuring a 240Hz holographic display and advanced neural processing unit.',
    imageUrl: '/images/phone.png',
    webLink: 'https://yubbox.com',
    ownerName: 'Sarah Chen',
    location: 'Silicon Valley, CA',
    companyName: 'Quantum Tech Labs',
    countries: ['US', 'JP', 'KR'],
    categoryId: mockCategoryProduct as unknown as mongoose.Types.ObjectId,
    industryId: mockIndustry as unknown as mongoose.Types.ObjectId,
    userId: mockUserId as unknown as mongoose.Types.ObjectId,
    isActive: true,
    isPaid: true,
    yubboxCount: 89,
    expiryDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: 'Global Digital Growth Strategy',
    description: 'Scaled your business globally with our data-driven digital marketing solutions. Specialized in SEO, PPC, and cross-border e-commerce transformation.',
    imageUrl: '/images/digital.png',
    webLink: 'https://yubbox.com',
    ownerName: 'Robert Vance',
    location: 'London, UK',
    companyName: 'Vance Digital Agency',
    countries: ['GB', 'DE', 'FR', 'AE'],
    categoryId: mockCategoryService as unknown as mongoose.Types.ObjectId,
    industryId: mockIndustry as unknown as mongoose.Types.ObjectId,
    userId: mockUserId as unknown as mongoose.Types.ObjectId,
    isActive: true,
    isPaid: true,
    yubboxCount: 256,
    expiryDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: 'Sustainable Smart Home Hub',
    description: 'The central brain for your eco-friendly home. Monitor energy usage, control appliances, and optimize your carbon footprint with AI insights.',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    webLink: 'https://yubbox.com',
    ownerName: 'Elena Rodriguez',
    location: 'Madrid, Spain',
    companyName: 'EcoSmart Solutions',
    countries: ['ES', 'PT', 'FR'],
    categoryId: mockCategoryProduct as unknown as mongoose.Types.ObjectId,
    industryId: mockIndustry as unknown as mongoose.Types.ObjectId,
    userId: mockUserId as unknown as mongoose.Types.ObjectId,
    isActive: true,
    isPaid: true,
    yubboxCount: 45,
    expiryDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: 'Artisan Coffee Roasters Collective',
    description: 'Direct trade beans sourced from family-owned farms. Roasted in small batches to preserve unique regional flavor profiles and aromas.',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    webLink: 'https://yubbox.com',
    ownerName: 'Marco Rossi',
    location: 'Florence, Italy',
    companyName: 'L’Artigiano Coffee',
    countries: ['IT', 'AT', 'CH'],
    categoryId: mockCategoryProduct as unknown as mongoose.Types.ObjectId,
    industryId: mockIndustry as unknown as mongoose.Types.ObjectId,
    userId: mockUserId as unknown as mongoose.Types.ObjectId,
    isActive: true,
    isPaid: true,
    yubboxCount: 78,
    expiryDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: 'CloudScale Infrastructure Management',
    description: 'Enterprise-grade cloud solutions powered by AI. Optimize your server costs, enhance security, and scale your applications globally with 99.99% uptime.',
    imageUrl: '/images/cloud.png',
    webLink: 'https://yubbox.com',
    ownerName: 'David Miller',
    location: 'Austin, TX',
    companyName: 'CloudScale Systems',
    countries: ['US', 'CA', 'GB'],
    categoryId: mockCategoryService as unknown as mongoose.Types.ObjectId,
    industryId: mockIndustry as unknown as mongoose.Types.ObjectId,
    userId: mockUserId as unknown as mongoose.Types.ObjectId,
    isActive: true,
    isPaid: true,
    yubboxCount: 142,
    expiryDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: 'Aura Architectural Design Studio',
    description: 'We create living spaces that inspire. specialized in luxury residential projects and sustainable commercial spaces with a focus on natural light.',
    imageUrl: '/images/architecture.png',
    webLink: 'https://yubbox.com',
    ownerName: 'Sophie Larousse',
    location: 'Paris, France',
    companyName: 'Aura Design',
    countries: ['FR', 'BE', 'LU'],
    categoryId: mockCategoryService as unknown as mongoose.Types.ObjectId,
    industryId: mockIndustry as unknown as mongoose.Types.ObjectId,
    userId: mockUserId as unknown as mongoose.Types.ObjectId,
    isActive: true,
    isPaid: true,
    yubboxCount: 187,
    expiryDate: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: 'Serenity Wellness Coaching',
    description: 'Transform your life with personalized wellness plans. We offer integrated physical health and mental clarity coaching in premium studio environments.',
    imageUrl: '/images/wellness.png',
    webLink: 'https://yubbox.com',
    ownerName: 'Emma Thompson',
    location: 'Vancouver, Canada',
    companyName: 'Serenity Wellness',
    countries: ['CA', 'US', 'AU'],
    categoryId: mockCategoryService as unknown as mongoose.Types.ObjectId,
    industryId: mockIndustry as unknown as mongoose.Types.ObjectId,
    userId: mockUserId as unknown as mongoose.Types.ObjectId,
    isActive: true,
    isPaid: true,
    yubboxCount: 95,
    expiryDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export const MOCK_CATEGORIES = [
  { _id: String(mockCategoryProduct), name: 'Premium Products', slug: 'products', type: 'product' as const },
  { _id: String(mockCategoryService), name: 'Strategic Services', slug: 'services', type: 'service' as const }
];
